{% set name = "dbt-common" %}
{% set version = "1.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 31f42029cccfdfe072d36abe649a479bad20b86ef711fe32de72411b9acd45c9
  patches:
    - patches/0001-update-protobuf-version.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - agate >=1.7.0,<1.10
    - colorama >=0.3.9,<0.5
    - dbt-protos >=1.0.291,<2.0.0
    - deepdiff >=7.0,<8.0
    - isodate >=0.6,<0.7
    - jsonschema >=4.0,<5.0
    - jinja2 >=3.1.3,<4
    - mashumaro >=3.9,<4.0
    - pathspec >=0.9,<0.13
    - protobuf >=5.0,<7.0
    - python-dateutil >=2.0,<3.0
    - requests <3.0.0
    - typing_extensions >=4.4,<5.0

test:
# Tests not included in pypi source, and github has no tagged releases.
  imports:
    - dbt_common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dbt-labs/dbt-common
  summary: The shared common utilities that dbt-core and adapter implementations use
  description: |
    The shared common utilities for dbt-core and adapter implementations use
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/dbt-labs/dbt-common
  doc_url: https://github.com/dbt-labs/dbt-common/tree/main/docs

extra:
  recipe-maintainers:
    - conda-forge/dbt
    - rxm7706
