{% set name = "dbt-common" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt_common-{{ version }}.tar.gz
  sha256: 68f4bf0d7fc7dfd939ebd4bec4c7e11814c7a98c281f7bfdca86a86f57de40f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - agate >=1.7.0,<1.10
    - colorama >=0.3.9,<0.5
    - isodate >=0.6,<0.7
    - jsonschema >=4.0,<5.0
    - jinja2 >=3.1.3,<4
    - mashumaro >=3.9,<4.0
    - pathspec >=0.9,<0.13
    - protobuf >=4.0.0,<5.0.0
    - python-dateutil >=2.0,<3.0
    - requests <3.0.0
    - typing-extensions >=4.4,<5.0

test:
  imports:
    - dbt_common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dbt-labs/dbt-common
  summary: The shared common utilities that dbt-core and adapter implementations use
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
