{% set name = "dbt-common" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dbt_common-{{ version }}.tar.gz
  sha256: 2227e24a165780c5368320dedd3c6bc40038dedece48af03daab43c11bf20372

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - pip
    - wheel
  run:
    - python
    - agate
    - colorama
    - deepdiff 
    - isodate 
    - jsonschema
    - jinja2 
    - mashumaro
    - pathspec
    - protobuf >=5.0,<6.0
    - python-dateutil
    - requests 
    - typing_extensions 

test:
  imports:
    - dbt_common
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/dbt-labs/dbt-common
  summary: The shared common utilities that dbt-core and adapter implementations use
  license: Apache-2.0
  license_file: LICENSE

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/63495
    reason: Dependency for dbt-core
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - conda-forge/dbt
    - rxm7706
